name: MCServerPlugin
version: '${project.version}'
main: me.core.MCServerPlugin
api-version: 1.18
authors: [ JJGP ]
description: A Paper server plugin
commands:
  mail:
    description: "Open your mailbox"
    usage: "/mail"
    aliases:
      - mailbox
  admin-mail:
    description: "Manage mail"
    usage: '/admin-mail'
    aliases:
      - amail
    permission: admin.mail
permissions:
  admin.mail:
    default: op