name: MCServerPlugin
version: '${project.version}'
main: me.core.MCServerPlugin
api-version: 1.18
authors: [ JJGP ]
description: A PaperMC server plugin
commands:
  menu:
    description: "Open menu"
    usage: "/menu"
  balance:
    description: "Query balance"
    usage: "/balance"
    aliases:
      - bal
      - money
  market:
    description: "Open market GUI"
    usage: "/market"
  mail:
    description: "Open your mailbox"
    usage: "/mail"
    aliases:
      - mailbox
  admin-economy:
    description: "Admin economy commands"
    usage: "/admin-economy"
    aliases:
      - admin-money
      - a-economy
      - a-money
    permission: admin.money
  admin-mail:
    description: "Manage mail commands"
    usage: '/admin-mail'
    aliases:
      - a-mail
    permission: admin.mail
  admin-container:
    description: "Admin container commands"
    usage: '/admin-container'
    aliases:
      - admin-case
      - a-container
      - a-case
    permission: admin.container
  admin-stattrak:
    description: "Admin StatTrak commands"
    usage: '/admin-stattrak'
    aliases:
      - a-stattrak
      - a-st
    permission: admin.stattrak
permissions:
  admin.*:
    default: op