name: MCServerPlugin
version: '${project.version}'
main: me.core.MCServerPlugin
api-version: 1.18
authors: [ JJGP ]
description: A PaperMC server plugin
commands:
  menu:
    description: "Open menu"
    usage: "/menu"
  money:
    description: "Query money"
    usage: "/money"
  mail:
    description: "Open your mailbox"
    usage: "/mail"
    aliases:
      - mailbox
  admin-money:
    description: "Admin money commands"
    usage: "/admin-money"
    aliases:
      - a-money
    permission: admin.money
  admin-mail:
    description: "Manage mail commands"
    usage: '/admin-mail'
    aliases:
      - a-mail
    permission: admin.mail
  admin-container:
    description: "Admin container commands"
    usage: '/admin-container'
    aliases:
      - admin-case
      - a-container
      - a-case
    permission: admin.container
  admin-stattrak:
    description: "Admin StatTrak commands"
    usage: '/admin-stattrak'
    aliases:
      - a-stattrak
      - a-st
    permission: admin.stattrak
permissions:
  admin.*:
    default: op